# -*- coding: utf-8 -*-
"""Survival Analysis - Exponential and Weibull function.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ax7I9-k29uIWF8Z1nxeoTf4WACkk58jr

Exponential and Weibull survival function, Hazard function, comparison of these functions, log rank test

##a) Exponential and Weibull survival function

**For the "stanford2" data from the "survival" package, determine survival curves for exponential and Weibull distributions. Compare the obtained survival curves with the Kaplan Meier curve.**
"""

library(survival)
data(stanford2)
attach(stanford2)
head(stanford2)

# Kaplan Meier curve
km = survfit(Surv(time, status)~ 1)
km

summary(km)

plot(km, col = 'red')

# comparison of age groups survival curves (higher and lower that median), caplan meier function
age2=rep(0, 184)
age2[age<median(age)] = 1
survfit(Surv(time,  status) ~ age2)
plot(survfit(Surv(time,  status) ~ age2), col = c('blue', 'red'), lwd =2)
grid()

# check if there is a significant difference between the two curves (
survdiff(Surv(time, status)~ age2)

"""P-value lower than 0.05, there is significant diffrence between this  groups. There is a diffrence in survival time.

**Exponential survival function**
"""

wyk = survreg(Surv(time, status)~ 1, data = stanford2, dist = 'exp')
wyk

""" The survival regression model with a constant term (intercept) is fitted to the data. The estimated coefficient for the intercept is 7.034251. The model assumes an exponential distribution for the survival times. The log-likelihood indicates the fit of the model to the data, and in this case, the model does not provide a significantly better fit than the intercept-only model. The sample size is 184, representing the number of individuals included in the analysis."""

# lambda exponential
lambda_wyk = exp(-wyk$coef)
lambda_wyk

"""**Weibull survival function**"""

wei = survreg(Surv(time, status)~1, data = stanford2, dist = 'weibull')
wei

"""The survival regression model with a constant term (intercept) is fitted to the data. The estimated coefficient for the intercept is 7.092712. The model assumes a Weibull distribution for the survival times, with a scale parameter estimated to be 1.804064. The log-likelihood indicates the fit of the model to the data, and in this case, the model does not provide a significantly better fit than the intercept-only model. The sample size is 184, representing the number of individuals included in the analysis."""

# lambda weibull
lambda_wei = exp(-wei$icoef[1])
lambda_wei

# kappa
kappa = 1/(exp(wei$icoef[2]))
kappa

# red exponential
# blue weibull
# black Kaplana Meiera
plot(km, col = "blue", lwd = 2, conf.int = FALSE)
x=seq(0,max(time),length=10000)
y_wei=exp(-(lambda_wyk*x)^kappa)
y_wyk=exp( - lambda_wyk * x)
lines(x, y_wyk, lwd = 2, col = "red")
lines(x, y_wei, lwd = 2, col = "darkgreen")
legend("topright", c("K-M","exp", "Weibull"), col=c("blue","red","darkgreen"), lwd = 2)

"""## b) Hazard functions

For the above survival functions, determine the hazard functions and determine their 95% intervals
confidence intervals.
"""

# exponential hazard function (lambda)

lambda_wyk = exp(-wyk$coef)
lambda_wyk

# sum of event
sd=sum(stanford2$status)
d
# (n_d = length(which(stanford2$status == 1)))

# standard error for exponential distribution
SE_wyk=sqrt(lambda_wyk/(d-1))
SE_wyk

# Confidence intervals for the exponential distribution hazards function
L_wyk = lambda_wyk-1.96*SE_wyk
L_wyk[L_wyk < 0] = 0
L_wyk
(U_wyk = round(lambda_wyk+1.96*SE_wyk, digits = 3))

# weibull hazard function (lambda)

lambda_wei = exp(-wei$icoef[1])
lambda_wei

# standard error for the weibull distribution
SE_wei=sqrt(lambda_wei/(d-1))
SE_wei

"""## c) Median and confidence interval

**For the above data, determine the median survival and its 95% confidence interval. What
would the median survival be for a curve based on an exponential distribution, and what for a survival curve based on a Weibull distribution?
survival based on a Weibull distribution?**
"""

# median and confidence interval

survfit(Surv(time,status)~1)

# Median exponential disribution

(k = which.min(abs(y_wyk-0.5)))
round(x[k], digits = 0)

# Median weibull distribution
(k = which.min(abs(y_wei-0.5)))
round(x[k], digits = 0)

"""## d) Log Rank test

**For the variable age, designate two groups: (i) under 45; (ii) over 45. Then, using
using the log-rank test, check whether there are significant differences between the survival curves
for these groups.**
"""

# Dividing the age variable into a group younger than 45 years and older/equivalent 45 years
stanford2$age3[stanford2$age < 45]= 1
stanford2$age3[stanford2$age >= 45]= 2
head(stanford2)

# the number of individual groups
table(stanford2$age3)

# survival curves for people divided by age3
km2 = survfit(Surv(time, status) ~ age3, data = stanford2)
km2

# Significance testing with the logrank test

survdiff(Surv(time, status) ~ age3, data = stanford2)

"""P-value lower than 0.05. There is significant diffrence. Age group is significant for survival time."""

pchisq(3.03+3.50, df = 1, lower.tail = FALSE)

"""## e) Median survival

**For the experiment from previos task, determine: (i) the hazard function ± 95% confidence intervals; (ii) the median survival for each group and the hazard function for the ratio of median survival between the two groups ± 95% confidence intervals.**
"""

# From this model we select the expected and observed values
survdiff(Surv(time, status) ~ age3, data = stanford2)

# (age2=1 observed /age2=1 expected) / (age2=2 observed /age2=2 expected)
HR4 <- (47/60.6)/(66/52.4)
HR4

"""We calculate the standard error from the formula, where Ea is the sum of expected events in group 1 and Eb in group 2"""

SE_logHR <-  sqrt(1/60.6 + 1/52.4)

# Confidence interval
L_HR <-  exp(log(HR)-1.96*SE_logHR)
U_HR <-  exp(log(HR)+1.96*SE_logHR)
L_HR
U_HR

# Median quotient
survfit(Surv(time, status) ~ age3, data = stanford2)

# Median quotient
HR_median = 1247/279
HR_median

# błąd standardowy ilorazu median
SE_logHR_median = sqrt(1/47 + 1/66)
# confidence intervals for the median quotient
(L_HR_median <-  exp(log(HR_median)-1.96*SE_logHR_median))
(U_HR_median <-  exp(log(HR_median)+1.96*SE_logHR_median))

